export const GLOBAL_ONBOARDING_MICROSERVICE_PORT = 5000;
export const GLOBAL_CONSOLE_MICROSERVICE_PORT = 5001;

export const GLOBAL_SERVICE_STATUS_PORT = 9998;

export const GLOBAL_WEATHER_MICROSERVICE_PORT = 5002

export const GLOBAL_SYSTEM_MICROSERVICE_PORT = 5003;